### ISSUE TITLE
Bits Per Sample & Sample Rate Conversions

### ISSUE THREAD

**Issue by Barough** [jessielw/FFMPEG-Audio-Encoder#43]
Would it be possible to add options to do Bits Per Sample & Sample Rate Conversions?

Example
24bit/96 kHz ->16bit/44.1 kHz

**Comment by jlw4049** [comment]
This shouldn't be too difficult to implement

**Comment by Barough** [comment]
Totally missed the Sample Rate option in there. ;)

Don't think i've every seen an lossy that's not 16-bit. As you say, 24-bit is seen in lossless files as FLAC, WavPack etc.

**Comment by Barough** [comment]
Any progress related to bit depth conversion or?
Just a little inquiry here ;)

**Comment by jessielw** [comment]
Hello,

Last we discussed above _(I know it's been a while)_, the only supported codec we use is **FLAC** for bit depth conversion. Utilizing SOX would be nice, but I haven't done any work on this. I've been working on LOTS of other tools, some closed source tools that I'll bring to light eventually. 

Explain to me exactly what you'd like to see and perhaps we can see about potentially adding it into the software! Remember, if there is a specific use case, you can **save a profile** with custom command line settings (like using SOX/bit depth for FLAC).

**Comment by Barough** [comment]
It was a friend of mine that asked i've heard anything more about this. I know there is other solutions available out there for bit depth conversion so i actually think we can let this one pass.

**Comment by jessielw** [comment]
> It was a friend of mine that asked i've heard anything more about this. I know there is other solutions available out there for bit depth conversion so i actually think we can let this one pass.

Alright! We'll, re-open an issue if you can think of anything else.
